# Generated by IconBlaster 1.1.3

for subdir in [0-9]*; do
dest="$1/$subdir"
mkdir -p "$dest" || return 1

install -m 644 $subdir/adjust-layout.png "$dest"
install -m 644 $subdir/adjust-scrollback.png "$dest"
install -m 644 $subdir/annotate.png "$dest"
install -m 644 $subdir/cancel-task.png "$dest"
install -m 644 $subdir/choose-color.png "$dest"
install -m 644 $subdir/choose-font.png "$dest"
install -m 644 $subdir/choose-icon.png "$dest"
install -m 644 $subdir/choose-item.png "$dest"
install -m 644 $subdir/clean.png "$dest"
install -m 644 $subdir/clear.png "$dest"
(cd "$dest" && ln -sf clear.png clear-alert.png)
install -m 644 $subdir/clear-scrollback.png "$dest"
install -m 644 $subdir/clone-item.png "$dest"
install -m 644 $subdir/clone-terminal.png "$dest"
install -m 644 $subdir/close-terminal.png "$dest"
(cd "$dest" && ln -sf close-terminal.png close-window.png)
install -m 644 $subdir/configure.png "$dest"
install -m 644 $subdir/connection-close.png "$dest"
install -m 644 $subdir/connection-launch.png "$dest"
install -m 644 $subdir/conntype-active.png "$dest"
install -m 644 $subdir/conntype-batch.png "$dest"
install -m 644 $subdir/conntype-container.png "$dest"
(cd "$dest" && ln -sf configure.png conntype-generic.png)
install -m 644 $subdir/conntype-named.png "$dest"
install -m 644 $subdir/conntype-persistent.png "$dest"
install -m 644 $subdir/conntype-root.png "$dest"
install -m 644 $subdir/conntype-ssh.png "$dest"
install -m 644 $subdir/conntype-transient.png "$dest"
install -m 644 $subdir/conntype-user.png "$dest"
(cd "$dest" && ln -sf clone-item.png copy.png)
install -m 644 $subdir/decrease-font.png "$dest"
install -m 644 $subdir/delete-file.png "$dest"
install -m 644 $subdir/destroy.png "$dest"
(cd "$dest" && ln -sf connection-close.png disconnect-server.png)
(cd "$dest" && ln -sf connection-close.png disconnect-terminal.png)
install -m 644 $subdir/download-file.png "$dest"
(cd "$dest" && ln -sf choose-icon.png download-image.png)
install -m 644 $subdir/duplicate-terminal.png "$dest"
install -m 644 $subdir/edit-global-settings.png "$dest"
install -m 644 $subdir/edit-icon-rules.png "$dest"
install -m 644 $subdir/edit-item.png "$dest"
install -m 644 $subdir/edit-keymap.png "$dest"
(cd "$dest" && ln -sf configure.png edit-profile.png)
(cd "$dest" && ln -sf configure.png edit-server.png)
install -m 644 $subdir/edit-switch-rules.png "$dest"
install -m 644 $subdir/event-log.png "$dest"
install -m 644 $subdir/execute.png "$dest"
install -m 644 $subdir/exit-full-screen.png "$dest"
install -m 644 $subdir/exit-pres-mode.png "$dest"
install -m 644 $subdir/extract-profile.png "$dest"
install -m 644 $subdir/fetch-image.png "$dest"
install -m 644 $subdir/filter.png "$dest"
install -m 644 $subdir/help-about.png "$dest"
install -m 644 $subdir/help-contents.png "$dest"
install -m 644 $subdir/help-homepage.png "$dest"
install -m 644 $subdir/help-totd.png "$dest"
install -m 644 $subdir/hide-item.png "$dest"
(cd "$dest" && ln -sf hide-item.png hide-server.png)
(cd "$dest" && ln -sf hide-item.png hide-terminal.png)
install -m 644 $subdir/highlight-cursor.png "$dest"
install -m 644 $subdir/highlight-regions.png "$dest"
install -m 644 $subdir/import-item.png "$dest"
install -m 644 $subdir/increase-font.png "$dest"
(cd "$dest" && ln -sf cancel-task.png input-unset-leader.png)
install -m 644 $subdir/insert-item.png "$dest"
install -m 644 $subdir/inspect-item.png "$dest"
install -m 644 $subdir/launchtype-default.png "$dest"
(cd "$dest" && ln -sf execute.png launchtype-run-local.png)
(cd "$dest" && ln -sf execute.png launchtype-run-remote.png)
(cd "$dest" && ln -sf conntype-persistent.png launchtype-term-local.png)
(cd "$dest" && ln -sf conntype-persistent.png launchtype-term-remote.png)
install -m 644 $subdir/launchtype-write.png "$dest"
install -m 644 $subdir/ls-format-long.png "$dest"
install -m 644 $subdir/ls-format-short.png "$dest"
install -m 644 $subdir/manage-alerts.png "$dest"
(cd "$dest" && ln -sf connection-launch.png manage-connections.png)
install -m 644 $subdir/manage-keymaps.png "$dest"
(cd "$dest" && ln -sf launchtype-default.png manage-launchers.png)
install -m 644 $subdir/manage-plugins.png "$dest"
install -m 644 $subdir/manage-port-forwarding.png "$dest"
install -m 644 $subdir/manage-profiles.png "$dest"
install -m 644 $subdir/manage-servers.png "$dest"
(cd "$dest" && ln -sf conntype-persistent.png manage-terminals.png)
install -m 644 $subdir/manpage-terminal.png "$dest"
install -m 644 $subdir/menu-favorites.png "$dest"
(cd "$dest" && ln -sf conntype-persistent.png menu-terminal.png)
install -m 644 $subdir/mount-file-ro.png "$dest"
install -m 644 $subdir/mount-file-rw.png "$dest"
install -m 644 $subdir/move-bottom.png "$dest"
install -m 644 $subdir/move-down.png "$dest"
install -m 644 $subdir/move-top.png "$dest"
install -m 644 $subdir/move-up.png "$dest"
(cd "$dest" && ln -sf insert-item.png new-item.png)
install -m 644 $subdir/new-terminal.png "$dest"
(cd "$dest" && ln -sf new-terminal.png new-terminal-local.png)
(cd "$dest" && ln -sf manage-servers.png new-terminal-server.png)
install -m 644 $subdir/new-window.png "$dest"
install -m 644 $subdir/next-server.png "$dest"
(cd "$dest" && ln -sf next-server.png next-terminal.png)
install -m 644 $subdir/open-directory.png "$dest"
install -m 644 $subdir/open-file.png "$dest"
(cd "$dest" && ln -sf conntype-persistent.png open-terminal.png)
(cd "$dest" && ln -sf help-homepage.png open-url.png)
(cd "$dest" && ln -sf launchtype-default.png open-with.png)
(cd "$dest" && ln -sf launchtype-write.png paste.png)
install -m 644 $subdir/pause.png "$dest"
(cd "$dest" && ln -sf execute.png plugin-action.png)
install -m 644 $subdir/plugin-disabled.png "$dest"
install -m 644 $subdir/plugin-parser.png "$dest"
(cd "$dest" && ln -sf help-totd.png plugin-totd.png)
install -m 644 $subdir/pop-profile.png "$dest"
install -m 644 $subdir/previous-server.png "$dest"
(cd "$dest" && ln -sf previous-server.png previous-terminal.png)
(cd "$dest" && ln -sf execute.png prompt.png)
install -m 644 $subdir/push-profile.png "$dest"
install -m 644 $subdir/quit-application.png "$dest"
(cd "$dest" && ln -sf annotate.png raise-annotations-tool.png)
install -m 644 $subdir/raise-files-tool.png "$dest"
install -m 644 $subdir/raise-history-tool.png "$dest"
(cd "$dest" && ln -sf edit-keymap.png raise-keymap-tool.png)
install -m 644 $subdir/raise-search-tool.png "$dest"
install -m 644 $subdir/raise-suggestions-tool.png "$dest"
install -m 644 $subdir/raise-tasks-tool.png "$dest"
(cd "$dest" && ln -sf conntype-persistent.png raise-terminals-tool.png)
install -m 644 $subdir/random-theme.png "$dest"
install -m 644 $subdir/reboot.png "$dest"
install -m 644 $subdir/reload.png "$dest"
install -m 644 $subdir/reload-all.png "$dest"
install -m 644 $subdir/remove-annotation.png "$dest"
(cd "$dest" && ln -sf remove-annotation.png remove-command.png)
install -m 644 $subdir/remove-item.png "$dest"
install -m 644 $subdir/rename-file.png "$dest"
(cd "$dest" && ln -sf rename-file.png rename-item.png)
install -m 644 $subdir/reorder.png "$dest"
(cd "$dest" && ln -sf next-server.png reorder-server-backward.png)
install -m 644 $subdir/reorder-server-first.png "$dest"
(cd "$dest" && ln -sf previous-server.png reorder-server-forward.png)
install -m 644 $subdir/reorder-server-last.png "$dest"
(cd "$dest" && ln -sf next-server.png reorder-terminal-backward.png)
(cd "$dest" && ln -sf reorder-server-first.png reorder-terminal-first.png)
(cd "$dest" && ln -sf previous-server.png reorder-terminal-forward.png)
(cd "$dest" && ln -sf reorder-server-last.png reorder-terminal-last.png)
(cd "$dest" && ln -sf reload.png reset.png)
(cd "$dest" && ln -sf reload.png reset-and-clear-terminal.png)
(cd "$dest" && ln -sf clear.png reset-icon.png)
(cd "$dest" && ln -sf clear.png reset-search.png)
(cd "$dest" && ln -sf reload.png reset-terminal.png)
install -m 644 $subdir/restart-task.png "$dest"
(cd "$dest" && ln -sf restart-task.png resume.png)
install -m 644 $subdir/save.png "$dest"
install -m 644 $subdir/save-all.png "$dest"
(cd "$dest" && ln -sf save-all.png save-as.png)
install -m 644 $subdir/save-screen.png "$dest"
(cd "$dest" && ln -sf next-server.png scroll-image.png)
(cd "$dest" && ln -sf move-down.png scroll-page-down.png)
(cd "$dest" && ln -sf move-up.png scroll-page-up.png)
(cd "$dest" && ln -sf move-top.png scroll-prompt-first.png)
(cd "$dest" && ln -sf move-bottom.png scroll-prompt-last.png)
(cd "$dest" && ln -sf reorder-server-last.png scroll-region-end.png)
(cd "$dest" && ln -sf reorder-server-first.png scroll-region-start.png)
(cd "$dest" && ln -sf move-bottom.png scroll-to-bottom.png)
(cd "$dest" && ln -sf move-top.png scroll-to-top.png)
(cd "$dest" && ln -sf raise-search-tool.png search.png)
(cd "$dest" && ln -sf close-terminal.png search-close.png)
install -m 644 $subdir/search-down.png "$dest"
install -m 644 $subdir/search-up.png "$dest"
install -m 644 $subdir/select.png "$dest"
(cd "$dest" && ln -sf destroy.png send-signal.png)
(cd "$dest" && ln -sf manage-alerts.png set-alert.png)
(cd "$dest" && ln -sf manage-profiles.png setup-tasks.png)
install -m 644 $subdir/show-item.png "$dest"
install -m 644 $subdir/show-menu-bar.png "$dest"
(cd "$dest" && ln -sf show-item.png show-server.png)
(cd "$dest" && ln -sf show-item.png show-terminal.png)
(cd "$dest" && ln -sf show-item.png show-terminals.png)
install -m 644 $subdir/shutdown.png "$dest"
install -m 644 $subdir/sort-ascending.png "$dest"
install -m 644 $subdir/sort-descending.png "$dest"
install -m 644 $subdir/split-view-close.png "$dest"
install -m 644 $subdir/split-view-close-others.png "$dest"
install -m 644 $subdir/split-view-equalize.png "$dest"
install -m 644 $subdir/split-view-equalize-all.png "$dest"
install -m 644 $subdir/split-view-expand.png "$dest"
(cd "$dest" && ln -sf split-view-equalize.png split-view-horizontal-fixed.png)
(cd "$dest" && ln -sf split-view-equalize.png split-view-horizontal-resize.png)
install -m 644 $subdir/split-view-quad-fixed.png "$dest"
install -m 644 $subdir/split-view-shrink.png "$dest"
install -m 644 $subdir/split-view-vertical-fixed.png "$dest"
(cd "$dest" && ln -sf split-view-vertical-fixed.png split-view-vertical-resize.png)
install -m 644 $subdir/submit-item.png "$dest"
(cd "$dest" && ln -sf next-server.png switch-item.png)
(cd "$dest" && ln -sf next-server.png switch-pane.png)
(cd "$dest" && ln -sf conntype-user.png take-terminal-ownership.png)
(cd "$dest" && ln -sf clean.png task-view-remove-tasks.png)
(cd "$dest" && ln -sf clone-item.png tasktype-copy-file.png)
(cd "$dest" && ln -sf delete-file.png tasktype-delete-file.png)
(cd "$dest" && ln -sf download-file.png tasktype-download-file.png)
(cd "$dest" && ln -sf choose-icon.png tasktype-download-image.png)
install -m 644 $subdir/tasktype-download-pipe.png "$dest"
(cd "$dest" && ln -sf fetch-image.png tasktype-fetch-image.png)
(cd "$dest" && ln -sf execute.png tasktype-local-command.png)
(cd "$dest" && ln -sf mount-file-rw.png tasktype-mount.png)
(cd "$dest" && ln -sf launchtype-write.png tasktype-paste-bytes.png)
(cd "$dest" && ln -sf launchtype-write.png tasktype-paste-file.png)
install -m 644 $subdir/tasktype-port-forward-in.png "$dest"
(cd "$dest" && ln -sf manage-port-forwarding.png tasktype-port-forward-out.png)
(cd "$dest" && ln -sf execute.png tasktype-remote-command.png)
(cd "$dest" && ln -sf rename-file.png tasktype-rename-file.png)
(cd "$dest" && ln -sf conntype-batch.png tasktype-run-batch.png)
(cd "$dest" && ln -sf connection-launch.png tasktype-run-connect.png)
install -m 644 $subdir/tasktype-upload-file.png "$dest"
(cd "$dest" && ln -sf tasktype-download-pipe.png tasktype-upload-pipe.png)
install -m 644 $subdir/timing-set-origin.png "$dest"
install -m 644 $subdir/toggle-command-mode.png "$dest"
install -m 644 $subdir/toggle-full-screen.png "$dest"
(cd "$dest" && ln -sf timing-set-origin.png toggle-marks-widget.png)
(cd "$dest" && ln -sf show-menu-bar.png toggle-menu-bar.png)
install -m 644 $subdir/toggle-minimap-widget.png "$dest"
install -m 644 $subdir/toggle-pres-mode.png "$dest"
install -m 644 $subdir/toggle-scrollbar-widget.png "$dest"
install -m 644 $subdir/toggle-status-bar.png "$dest"
install -m 644 $subdir/toggle-terminal-remote-input.png "$dest"
install -m 644 $subdir/toggle-timing-widget.png "$dest"
install -m 644 $subdir/toggle-tool-search-bar.png "$dest"
(cd "$dest" && ln -sf show-menu-bar.png toggle-tool-table-header.png)
(cd "$dest" && ln -sf insert-item.png tool-filter-add-server.png)
(cd "$dest" && ln -sf insert-item.png tool-filter-add-terminal.png)
(cd "$dest" && ln -sf remove-item.png tool-filter-exclude-server.png)
(cd "$dest" && ln -sf remove-item.png tool-filter-exclude-terminal.png)
install -m 644 $subdir/tool-filter-include-nothing.png "$dest"
(cd "$dest" && ln -sf clean.png tool-filter-remove-closed.png)
(cd "$dest" && ln -sf clear.png tool-filter-reset.png)
(cd "$dest" && ln -sf filter.png tool-filter-set-server.png)
(cd "$dest" && ln -sf filter.png tool-filter-set-terminal.png)
(cd "$dest" && ln -sf toggle-tool-search-bar.png tool-search.png)
(cd "$dest" && ln -sf clear.png tool-search-reset.png)
(cd "$dest" && ln -sf pop-profile.png undo-all-adjustments.png)
(cd "$dest" && ln -sf tasktype-upload-file.png upload-dir.png)
(cd "$dest" && ln -sf tasktype-upload-file.png upload-file.png)
(cd "$dest" && ln -sf inspect-item.png view-server-info.png)
(cd "$dest" && ln -sf fetch-image.png view-terminal-content.png)
(cd "$dest" && ln -sf inspect-item.png view-terminal-info.png)
(cd "$dest" && ln -sf launchtype-write.png write-command.png)
(cd "$dest" && ln -sf submit-item.png write-command-newline.png)
(cd "$dest" && ln -sf launchtype-write.png write-directory-path.png)
(cd "$dest" && ln -sf launchtype-write.png write-file-path.png)

done
